services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - /etc/xrobotics/secrets/.env
    volumes:
      - ./backend:/app
      - /home/ubuntu/xcubes/:/data:ro
      - /home/ubuntu/logs/robot_viewer/:/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      target: dist
    volumes:
      - frontend_dist:/dist
    command: ["/bin/sh", "-c", "cp -r ./* /dist"]

volumes:
  frontend_dist: