services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - /etc/xrobotics/secrets/.env
    volumes:
      - ./backend:/app
      - /home/ubuntu/xcubes/:/data:ro
      - /home/ubuntu/logs/robot_viewer/:/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # frontend: deploy by make deploy command